- scripts/project-sim.mk
Beside test name, add also folder name in generated xml.
Generate JUnit files also  for passed tests.
> scripts/project-sim.mk: Optimizations

- pulsar_adc_pmdz/Makefile
- pulsar_adc_pmdz/README.md
- pulsar_adc_pmdz/cfgs/cfg1.tcl
- pulsar_adc_pmdz/system_bd.tcl
- pulsar_adc_pmdz/system_project.tcl
- pulsar_adc_pmdz/system_tb.sv
- pulsar_adc_pmdz/tests/test_program.sv
- pulsar_adc_pmdz/waves/cfg1.wcfg
Testbench for ad7xxx pulsar adc pmods
> pulsar_adc_pmdz: Initial commit

- common/sv/adi_jesd204_pkg.sv
- common/sv/adi_xcvr_pkg.sv
adi_jesd204_pkg.sv: Link state encoding and sysref_clk verification
adi_xcvr_pkg.sv: Explicit PLL selection
> adi_jesd204_pkg.sv, adi_xcvr_pkg.sv: bug fixes

- pulsar_adc_pmdz/tests/test_program.sv
- pulsar_adc_pmdz/waves/cfg1.wcfg
> pular_adc: Fix test program

- data_offload/Makefile
- data_offload/cfgs/cfg1.tcl
- data_offload/cfgs/cfg2.tcl
- data_offload/cfgs/cfg3.tcl
- data_offload/cfgs/cfg7_internal_memory.tcl
- data_offload/system_bd.tcl
- data_offload/tests/test_program.sv
- data_offload_2/Makefile
- data_offload_2/cfgs/cfg0.tcl
- data_offload_2/cfgs/cfg1.tcl
- data_offload_2/cfgs/cfg2.tcl
- data_offload_2/cfgs/cfg3.tcl
- data_offload_2/cfgs/cfg4.tcl
- data_offload_2/cfgs/cfg5_hbm.tcl
- data_offload_2/cfgs/cfg5_hbm_cyclic.tcl
- data_offload_2/system_bd.tcl
- data_offload_2/system_tb.sv
- data_offload_2/tests/test_program.sv
- data_offload_2/tests/test_program_sync.sv
- hbm/Makefile
- hbm/README.md
- hbm/cfgs/cfg1.tcl
- hbm/system_bd.tcl
- hbm/system_project.tcl
- hbm/system_tb.sv
- hbm/tests/test_program.sv
- hbm/waves/cfg1.wcfg
These changes fixes the data offload testbenches and update to use the util_hbm.
> Data offload TBs

- ad9083/Makefile
- ad9083/system_bd.tcl
- ad9083/tests/test_program.sv
- ad_quadmxfe1_ebz/cfgs/cfg1.tcl
- ad_quadmxfe1_ebz/system_project.tcl
- ad_quadmxfe1_ebz/tests/test_program.sv
- common/sv/adi_jesd204_pkg.sv
- mxfe/Makefile
- mxfe/tests/test_program.sv
The following testbenches are updated:
1. ad9083
2. mxfe
3. ad_quadmxfe1_ebz
> Testbench improvements

- ad463x/tests/test_program.sv
- pulsar_adc_pmdz/tests/test_program.sv
This reverts commit fb7be1cbbe6abd061dd41034c54c25c3979a088f.
> Revert "Fix ddr baddr (#29)"

- common/test_harness/test_harness_system_bd.tcl
- mxfe/cfgs/cfg6_m16_l8_tdd.tcl
- mxfe/system_bd.tcl
- mxfe/system_project.tcl
- mxfe/tests/test_program.sv
- mxfe/waves/cfg1.wcfg
> Dev data offload

- ad7616/Makefile
- ad7616/README.md
- ad7616/cfgs/cfg_pi.tcl
- ad7616/cfgs/cfg_si.tcl
- ad7616/system_bd.tcl
- ad7616/system_project.tcl
- ad7616/system_tb.sv
- ad7616/tests/test_program_pi.sv
- ad7616/tests/test_program_si.sv
- ad7616/waves/cfg_pi.wcfg
- ad7616/waves/cfg_si.wcfg
Add support for AD7616 testbench for both serial and parallel modes.
> ad7616_tb: Initial commit

- axi_tdd/Makefile
- axi_tdd/README.md
- axi_tdd/cfgs/cfg1.tcl
- axi_tdd/system_bd.tcl
- axi_tdd/system_project.tcl
- axi_tdd/system_tb.sv
- axi_tdd/tests/test_program.sv
- axi_tdd/waves/cfg1.wcfg
- common/sv/adi_regmap_tdd_gen_pkg.sv
- common/sv/adi_regmap_tdd_trans_pkg.sv
- scripts/adi_sim.tcl
Adds a new testbench for the generic TDD engine - axi_tdd
> New testbench: axi_tdd 

- common/sv/axi_dmac_pkg.sv
- common/sv/dmac_api.sv
Includes the transfer length alignment relaxing for MM interfaces in the verification environment.
> DMA transfer length alignment update

- common/sv/adi_regmap_pkg.sv
- scripts/adi_sim.tcl
- Added option for Write only registers
- Added UpdateRegister option for easier register value updating
- Added GetResetValue to retrieve default field value
> scripts and common: New functions

- ad463x/tests/test_program.sv
- ad7606x/tests/test_program.sv
- ad7616/tests/test_program_pi.sv
- ad7616/tests/test_program_si.sv
- ad9083/system_bd.tcl
- ad_quadmxfe1_ebz/tests/test_dma.sv
- ad_quadmxfe1_ebz/tests/test_program.sv
- ad_quadmxfe1_ebz/tests/test_program_64b66b.sv
- adrv9001/tests/test_program.sv
- adrv9009/tests/test_program.sv
- axi_tdd/tests/test_program.sv
- common/sv/test_harness_env.sv
- common/test_harness/test_harness_system_bd.tcl
- dma_loopback/tests/test_program.sv
- fmcomms2/tests/test_program.sv
- hbm/tests/test_program.sv
- jesd_loopback/tests/test_program.sv
- jesd_loopback_64b/tests/test_program.sv
- mxfe/tests/test_program.sv
- pulsar_adc_pmdz/tests/test_program.sv
- pulsar_adc_pmdz/tests/test_sleep_delay.sv
- scripts/adi_sim.tcl
- Added missing system reset for DDR memory
- Added reset interface and functions into the test_environment
- Updated all of the test_programs that were affected by the changes
> test_harness: Update

- ad_quadmxfe1_ebz/cfgs/cfg1.tcl
- ad_quadmxfe1_ebz/cfgs/cfg2_64b66b.tcl
- ad_quadmxfe1_ebz/cfgs/cfg3_64b66b_LR_4_125.tcl
- ad_quadmxfe1_ebz/cfgs/cfg4_64b66b_Tx10_Rx11.tcl
- ad_quadmxfe1_ebz/cfgs/cfg5_64b66b_Tx23_Rx25_LR_24_75.tcl
- ad_quadmxfe1_ebz/cfgs/cfg6_64b66b_Tx29_Rx24_LR_24_75.tcl
- ad_quadmxfe1_ebz/tests/test_dma.sv
- ad_quadmxfe1_ebz/tests/test_program.sv
- ad_quadmxfe1_ebz/tests/test_program_64b66b.sv
Checked all of the builds on Jenkins server with the main HDL repository. All passed. 
If you'd like to check them yourself, know that it took 8h+ on the CI server.
> ad_quadmxfe: Fix after IP update

- common/sv/m_axis_sequencer.sv
- data_offload/tests/test_program.sv
- data_offload_2/tests/test_program.sv
- data_offload_2/tests/test_program_sync.sv
- Changed active wait for data into event waits
- Updated order of execution of statments in data buffer according to the m_axis_sequencer requirements
> m_axis_sequencer: Fixes

- common/sv/interfaces.svh
Initial interface file for common interfaces. 
Added a clocking interface so it's easier to be controlled from classes, where the clocks will be the same in every simulation.
> Interfaces

- common/sv/test_harness_env.sv
- Relaxed the reset function, extending the time held in reset and giving enough time for the system to recover
> test_harness: Reset function fix

- common/sv/adi_regmap_i3c_controller_pkg.sv
- i3c_controller/Makefile
- i3c_controller/README.md
- i3c_controller/cfgs/cfg1.tcl
- i3c_controller/system_bd.tcl
- i3c_controller/system_project.tcl
- i3c_controller/system_tb.sv
- i3c_controller/tests/test_program.sv
- i3c_controller/waves/cfg1.wcfg
Standalone testbench to assert the implemented features.
Tests https://github.com/analogdevicesinc/hdl/pull/1267
> i3c_controller: Add testbench project

- axi_tdd/cfgs/cfg1.tcl
- axi_tdd/system_bd.tcl
- dma_loopback/cfgs/cfg1.tcl
- dma_loopback/system_bd.tcl
- scripts/adi_sim.tcl
Parameters are automatically written into parameters.log file inside the project creation folder, under runs/<cfg_name>/.
This will help with debugging when randomized testbenches are created.
> script_update: Write parameters into parameters.log where the project is created

- ad738x/Makefile
- ad738x/README.md
- ad738x/cfgs/cfg1.tcl
- ad738x/system_bd.tcl
- ad738x/system_project.tcl
- ad738x/system_tb.sv
- ad738x/tests/test_program.sv
Add testbench for ad738x project.
> AD738x testbench

- common/sv/spi_engine_instr_pkg.sv
- spi_engine/tests/test_program.sv
- spi_engine/tests/test_sleep_delay.sv
Improve spi_engine_instr_pkg, get version from regmap
> SPI Engine: improve instruction macros

- common/sv/m_axis_sequencer.sv
- Added clear queue option
- Fixed and improved stop policies
> m_axis_sequencer: Update

- common/test_harness/test_harness_system_bd.tcl
test_harness: Updated naming according to HDL changes
> TCL: ad_hpmx_interconnect

- docs/testbenches/project_based/ad463x/ad463x_tb.svg
- docs/testbenches/project_based/ad463x/index.rst
- docs/testbenches/project_based/index.rst
Add documentation support for the AD463X testbench.
> docs: Add ad463x doc support

- docs/testbenches/project_based/ad738x/ad738x_tb.svg
- docs/testbenches/project_based/ad738x/index.rst
- docs/testbenches/project_based/index.rst
Add support for ad738x testbenches documentation.
> Add ad738x doc

- README.md
Added link to Testbenches documentation and EngineerZone
> README.md: header update

- docs/testbenches/project_based/ad7606/ad7606x_tb.svg
- docs/testbenches/project_based/ad7606/index.rst
- docs/testbenches/project_based/index.rst
Add documentation support for the ad7606 testbench.
> docs: Add ad7606 doc

- testbenches/ip/dma_flock/environment.sv
- testbenches/ip/dma_flock/scoreboard.sv
- testbenches/ip/dma_flock/tests/test_program.sv
- testbenches/ip/dma_flock/tests/test_program_frame_delay.sv
Updated DMA framelock testbench after logger merging.
> logger: Fixed dma_flock

- docs/testbenches/ip_based/i3c_controller/block_diagram.svg
- docs/testbenches/ip_based/i3c_controller/index.rst
Merge after #154.
Considering main testbench, not the (future) rework.
>  docs: Add ip_based i3c_controller testbench 

- .github/PULL_REQUEST_TEMPLATE.md
> pull_request_template_update: Added Documentation PR Type

- testbenches/project/adrv9009/Makefile
- testbenches/project/adrv9009/cfgs/cfg1.tcl
- testbenches/project/adrv9009/cfgs/cfg2.tcl
- testbenches/project/adrv9009/cfgs/cfg3.tcl
- testbenches/project/adrv9009/cfgs/cfg4.tcl
- testbenches/project/adrv9009/system_bd.tcl
- testbenches/project/adrv9009/system_tb.sv
This commit updates the testbench to support the data offload integration.
> adrv9009: Add support for Data Offload

- docs/testbenches/project_based/ad7616/ad7616_pi_tb.svg
- docs/testbenches/project_based/ad7616/ad7616_si_tb.svg
- docs/testbenches/project_based/ad7616/index.rst
Add ad7616 testbench documentation.
> docs: Add ad7616 doc

- docs/testbenches/project_based/ad463x/index.rst
- docs/testbenches/project_based/ad738x/index.rst
- docs/testbenches/project_based/ad7606/index.rst
- docs/testbenches/project_based/ad7616/index.rst
- docs/testbenches/project_based/pulsar_adc/index.rst
- docs/testbenches/project_based/template/_index.rst
Improve uppercase and lowercase naming consistency, fix typos and replace "here" to the actual IP names across project based testbenches documentation.
> docs/testbenches: Improve consistency

- docs/testbenches/project_based/fmcomms2/fmcomms2_tb.svg
- docs/testbenches/project_based/fmcomms2/index.rst
Add FMCOMSM2 testbench documentation.
> docs: Add fmcomms2 doc

- docs/library/drivers/common/index.rst
Updated toctree after removing the monitor documentation.
> docs: Fixed toctree

- docs/user_guide/docs_guidelines.rst
Added documentation guidelines referring to class hierarchy implementation.
> docs: Updated documentation guidelines referring to class hierarchy

- docs/testbenches/project_based/pluto/index.rst
- docs/testbenches/project_based/pluto/pluto_tb.svg
Add pluto testbench documentation.
> docs: Add pluto doc

- docs/library/vip/amd/clk_vip/index.rst
- docs/library/vip/amd/rst_vip/index.rst
Updated documentation for AMD's clocking and reset VIPs.
> docs/library/vip/amd: Updated documentation

- testbenches/project/adrv9009/Makefile
- testbenches/project/adrv9009/system_bd.tcl
Fixed Data Offload dependencies and script pathing for JESD exerciser
> adrv9009: Fixed dependencies and script pathing

- docs/testbenches/ip_based/util_axis_fifo_asym/index.rst
- docs/testbenches/ip_based/util_axis_fifo_asym/util_axis_fifo_asym.svg
Added documentation for the util_axis_fifo_asym IP.
To be reviewed with #77
> Doc Util AXIS FIFO Asymmetric

- docs/testbenches/ip_based/util_axis_fifo/index.rst
- docs/testbenches/ip_based/util_axis_fifo/util_axis_fifo.svg
Added documentation for the util_axis_fifo IP.
To be reviewed with #161
> Doc Util AXIS FIFO

- library/drivers/dmac/dmac_api.sv
- testbenches/ip/data_offload/tests/test_program.sv
- testbenches/ip/dma_flock/tests/test_program.sv
- testbenches/ip/dma_flock/tests/test_program_frame_delay.sv
- testbenches/ip/dma_loopback/tests/test_program.sv
- testbenches/ip/scoreboard/tests/test_program.sv
- testbenches/ip/spi_engine/tests/test_program.sv
- testbenches/ip/spi_engine/tests/test_sleep_delay.sv
- testbenches/ip/spi_engine/tests/test_slowdata.sv
- testbenches/ip/util_pack/tests/test_program.sv
Minor updates for the DMAC API.
Updated the affected testbenches as well.
> library/drivers/dmac_api: Minor updates

- testbenches/project/fmcomms2/Makefile
- testbenches/project/fmcomms2/system_project.tcl
- testbenches/project/fmcomms2/tests/test_program.sv
Updated the fmcomms2 project function calls to use the implemented API packages.
> fmcomms2: Updated testbench to use API packages

- docs/testbenches/project_based/template/_index.rst
Update project template with latest changes.
> Doc project template update

- docs/testbenches/project_based/template/_index.rst
Fixes the Interrupt list definition. It now resembles the way HDL documentation handles these values.
> docs/project_template: Fix Interrupt list definition

- docs/testbenches/project_based/ad9083/ad9083_tb.svg
- docs/testbenches/project_based/ad9083/index.rst
- testbenches/project/ad9083/system_bd.tcl
- testbenches/project/ad9083/tests/test_program.sv
Docs: Add ad9083 testbench documentation
Testbenches/ad9083: Update test_program comments & fix duplicate addresses in system_bd
> Add ad9083 tb doc

- docs/testbenches/project_based/template/_index.rst
Updated project template documentation to use table directive instead of manual table creation.
> docs/project_template: Updated tables to use directive

- docs/testbenches/project_based/ad9083/index.rst
Fixes indentation and bullet list in the documentation for AD9083.
> docs/project/ad9083: Fixed indentations and bullet list

- docs/testbenches/ip_based/jesd_loopback/index.rst
- docs/testbenches/ip_based/jesd_loopback/jesd_loopback_tb.svg
- testbenches/ip/jesd_loopback/cfgs/cfg2.tcl
- testbenches/ip/jesd_loopback/cfgs/cfg2_np12.tcl
- testbenches/ip/jesd_loopback/cfgs/cfg3_np12_L2M8.tcl
- testbenches/ip/jesd_loopback/cfgs/cfg5_64b66b.tcl
- testbenches/ip/jesd_loopback/cfgs/cfg7_np12_L12M2.tcl
Add documentation for jesd_loopback ip-based testbench.
> docs: Add jesd_loopback tb doc

- docs/user_guide/hierarchy.rst
- docs/user_guide/index.rst
Renamed Testbenches architecture to Repository hierarchy.
Testbenches architecture will be a new section that goes into details on how the testbenches are structured and run.
> doc/hierarchy: Renamed Testbenches architecture to hierarchy

- docs/user_guide/build_tb.rst
Updated the section order on how to build a testbench, which makes more sense from a user's perspective.
Updated build requirements.
> docs/build_tb: Updated section order and updated requirements

- docs/user_guide/releases.rst
Updated release versions page.
- Added missing releases
- Updated links
> docs/releases: Updated release versions

- docs/testbenches/ip_based/axis_sequencers/index.rst
- docs/testbenches/ip_based/base/index.rst
- docs/testbenches/ip_based/dma_flock/index.rst
- docs/testbenches/ip_based/i3c_controller/index.rst
- docs/testbenches/ip_based/jesd_loopback/index.rst
- docs/testbenches/ip_based/util_axis_fifo/index.rst
- docs/testbenches/ip_based/util_axis_fifo_asym/index.rst
- docs/testbenches/ip_based/util_pack/index.rst
- docs/testbenches/project_based/ad463x/index.rst
- docs/testbenches/project_based/ad738x/index.rst
- docs/testbenches/project_based/ad7606/index.rst
- docs/testbenches/project_based/ad7616/index.rst
- docs/testbenches/project_based/ad9083/index.rst
- docs/testbenches/project_based/fmcomms2/index.rst
- docs/testbenches/project_based/pluto/index.rst
- docs/testbenches/project_based/pulsar_adc/index.rst
- docs/testbenches/project_based/template/_index.rst
Added simulation termination sequence to documentations.
Updated dependency naming for clarity.
> docs: Added simulation termination sequence to documentations

- docs/index.rst
- docs/library/drivers/common/watchdog/index.rst
- docs/library/vip/amd/axi_vip/adi_axi_agent.rst
- docs/library/vip/amd/axi_vip/adi_axi_monitor.rst
- docs/library/vip/amd/axis_vip/adi_axis_agent.rst
- docs/library/vip/amd/axis_vip/adi_axis_monitor.rst
- docs/library/vip/amd/axis_vip/m_axis_sequencer.rst
- docs/testbenches/index.rst
- docs/testbenches/ip_based/axis_sequencers/index.rst
- docs/testbenches/ip_based/dma_flock/index.rst
- docs/testbenches/ip_based/jesd_loopback/index.rst
- docs/testbenches/ip_based/util_pack/index.rst
- docs/testbenches/project_based/ad7616/index.rst
- docs/testbenches/project_based/template/_index.rst
- docs/user_guide/build_tb.rst
- docs/user_guide/create_edit_tb.rst
- docs/user_guide/docs_guidelines.rst
- docs/user_guide/git_repository.rst
Updated warnings and messages according to the Sphinx message directives documentation.
> docs: Updated warnings and messages

- library/drivers/i3c_controller_api_pkg.sv
- library/includes/Makeinclude_i3c_controller.mk
- library/includes/sp_include_i3c_controller.tcl
- library/regmaps/adi_regmap_i3c_controller_pkg.sv
- library/regmaps/adi_regmap_pkg.sv
- testbenches/ip/i3c_controller/Makefile
- testbenches/ip/i3c_controller/tests/test_program.sv
Transition to use API to access the I3C IP and fix simulation stalling.
> I3C API and fix

- docs/testbenches/ip_based/dma_loopback/dma_loopback_tb.svg
- docs/testbenches/ip_based/dma_loopback/index.rst
- testbenches/ip/dma_loopback/Makefile
- testbenches/ip/dma_loopback/system_project.tcl
Add dma_loopback testbench documentation.
> docs/ip: Add dma_loopback tb doc

- testbenches/project/ad7616/Makefile
- testbenches/project/ad7616/cfgs/cfg_pi.tcl
- testbenches/project/ad7616/cfgs/cfg_si_sdi2.tcl
- testbenches/project/ad7616/system_bd.tcl
- testbenches/project/ad7616/system_tb.sv
- testbenches/project/ad7616/tests/test_program_si.sv
Updates according to the new ad7616 HDL project
> ad7616: Add NUM_OF_SDI parameter

- docs/user_guide/debug_tb.rst
- docs/user_guide/index.rst
Added a debugging a testbench section to the documentation that detail how to enable logging messages, add new logging messages and how to replicate someone else's simulation results.
> docs: Added debugging a testbench section

- testbenches/project/ad7616/tests/test_program_si.sv
For 2024.2 version of Vivado it was encountering an issue regarding the dma data transfer, where a complete data transfer was not performed.
> ad7616: Fix dma data transfer

- docs/testbenches/project_based/ad57xx/ad57xx_ardz_tb.svg
- docs/testbenches/project_based/ad57xx/index.rst
- testbenches/project/ad57xx/cfgs/cfg1.tcl
Add documentation for the ad57xx testbench
> Ad57xx doc

- testbenches/ip/spi_engine/waves/cfg00.wcfg
- testbenches/ip/spi_engine/waves/cfg01.wcfg
- testbenches/ip/spi_engine/waves/cfg10.wcfg
- testbenches/ip/spi_engine/waves/cfg11.wcfg
- testbenches/ip/spi_engine/waves/cfg_inv_cs.wcfg
- testbenches/ip/spi_engine/waves/cfg_sdo_streaming.wcfg
cfg00 was broken. This PR fixes cfg00 and makes all the other wcfg the same (removes some signals which are not relevant for all tests).
> testbenches/ip/spi_engine: fix and uniformize wcfg files
