scripts/project-sim.mk
Add ^ in grep command in order to search for "error" or "fail"
only at the beggining of the lines.
This change is affecting only generation of jenkins Junit File.
=> scripts:project-sim.mk: Fix false failures

jesd_loopback/system_bd.tcl, jesd_loopback/system_tb.sv, jesd_loopback/tests/test_program.sv, jesd_loopback/waves/cfg1.wcfg
These commits match the following hdl changes:
https://github.com/analogdevicesinc/hdl/pull/789
=> jesd_loopback: Enable external SYNC for DAC path

adrv9009/Makefile, adrv9009/README.md, adrv9009/cfgs/cfg1.tcl, adrv9009/cfgs/cfg2.tcl, adrv9009/cfgs/cfg3.tcl, adrv9009/cfgs/cfg4.tcl, adrv9009/cfgs/cfg5.tcl, adrv9009/cfgs/cfg6.tcl, adrv9009/cfgs/cfg7.tcl, adrv9009/cfgs/cfg8.tcl, adrv9009/environment.sv, adrv9009/system_bd.tcl, adrv9009/system_project.tcl, adrv9009/system_tb.sv, adrv9009/tests/test_program.sv, adrv9009/waves/cfg1.wcfg, common/sv/adi_jesd204_pkg.sv, common/sv/adi_xcvr_pkg.sv, common/test_harness/test_harness_system_bd.tcl
- This testbench supports link layer loop back for every link(TX, RX. RX_OBSERVATION) implemented with jesd_exercisers
- Supports DMA/DDS tests for every link
- CFG files support JESD configurations only with NP=16 and F<8
- RX and RX_OBSERVATION links work with maximum of 2 lanes each
=> adrv9009 testbench

common/sv/adi_regmap_dmac_pkg.sv, common/sv/axi_dmac_pkg.sv, common/sv/dmac_api.sv, dma_loopback/tests/test_program.sv
1. Removed the DMA_2D_TRANSFER functions; used a write-read procedure to determine its value instead
2. Updated the DDR_BASE for the dma_loopback test
=> DMA testbench related updates

adrv9009/system_bd.tcl, adrv9009/tests/test_program.sv
adrv9009 TB stopped working after applying this commit: https://github.com/analogdevicesinc/testbenches/commit/91146665e3f73795cb1f69bf66f377b5ee7d535e
Made some changes to make it work and also simplified the check_captured_data task!
=> adrv9009: Fix TB for connected MNG VIP with DDR VIP

adrv9001/tests/test_program.sv, fmcomms2/tests/test_program.sv
Version 1:
- Updated minor version to the current one (32'h000a0262 -  in hdl master [branch](https://github.com/analogdevicesinc/hdl/blob/master/library/common/up_adc_common.v) - [commit](https://github.com/analogdevicesinc/hdl/commit/045327c8dbf14ad166b275389252e0756d8ba8b6);
=> adrv9001/fmmcoms2: Fix up_adc_common minor version in sanity test

mxfe/Makefile, mxfe/cfgs/cfg6_m16_l8_tdd.tcl, mxfe/system_bd.tcl, mxfe/system_project.tcl, mxfe/tests/test_program.sv
- The mxfe testbench needs to be updated since it now integrates the generic TDD engine.
- Updated the included package file, as well as the new register values.
=> mxfe: Update the sim to be compatible with the Generic TDD engine

fmcomms2/tests/test_program.sv
Updated the testbench to reflect the changes in RTL.
=> fmcomms2: Update the expected ADC Common Register Version

adrv9001/tests/test_program.sv
Update sanity test with latest VERSION regs' values and 'h8c reg's functionality;
- 'h8c will be the register dedicated to the control of ADCs by using RD/WR pins in case of using a custom interface (non-SPI) for configuration;
=> tb/adrv9001: Fix up_adc_common-based sanity test

common/test_harness/test_harness_system_bd.tcl, pulsar_adc_pmdz/system_project.tcl, scripts/adi_sim.tcl
Use SmartConnect global variable sets to use SmartConnect or AXI Interconnect for both cpu and mem.
By default, it is set to 1.
Should be merged alongside analogdevicesinc/hdl#1054 .
=> common: add use_smartconnect option

pulsar_adc_pmdz/Makefile
I think the current default approach of having a single test program to run at every configuration is counter-intuitive.
I updated the pulsar_adc Makefile to take an array of programs, and then **for each test program** and **for each cfg**, run the testbench.
For the pulsar_adc that means ``make`` runs both test_program and  test_sleep_delay run in cfg1.
Of course, we could do it manually:
```
TESTS += cfg1:test_program 
TESTS += cfg1:test_sleep_delay
```
but the whole point of this pr and discussion is to default running all tbs in all cfgs.
If this idea is well received, I would update all tbs to use ``addprefix``, except the ones that define ``TESTS`` manually.
=> Default running all tbs in all cfgs

data_offload/Makefile, data_offload_2/Makefile
Adds missing library dependency to the Makefiles.
=> data_offload: Add missing library dependency

scripts/project-sim.mk
- Build the project first using make
- Run the simulation only with make RUN=sim after the build is created
This is intended to be used mainly for repeated simulations, where the project or simulation files are finalized and we want to run the tests repeatedly one after another.
=> scripts: No config rebuild

ad7616/cfgs/cfg_pi.tcl, ad7616/cfgs/cfg_si.tcl, ad7616/system_bd.tcl, ad7616/system_project.tcl, ad7616/system_tb.sv, ad7616/tests/test_program_pi.sv, ad7616/tests/test_program_si.sv, ad7616/waves/cfg_pi.wcfg, ad7616/waves/cfg_si.wcfg
This commit fixes both the serial and parallel interface tests. These modifications reflect the HDL reference design updates:
1. The following IPs have been added: 
- axi_clkgen
- axi_pwm_gen
2. The configuration build parameter has been renamed to SER_PAR_N, set by default to 1, using the serial configuration.
=> ad7616: Update tb

.gitignore, scripts/project-sim.mk
* Print different line for start and finish process (e.g. `Running ....` and `Run OK`), so when running in parallel `make -j` the console log is not scrambled.
<details>
<summary>Example output, jesd_loopback with 5 parallel runs</summary>
```
jesd_loopback$ make -j5
Building cfg1 env [/home/me/Documents/adi/hdl/testbenches/jesd_loopback/runs/cfg1/system_project.log] ...
Building cfg2 env [/home/me/Documents/adi/hdl/testbenches/jesd_loopback/runs/cfg2/system_project.log] ...
Building cfg2_np12 env [/home/me/Documents/adi/hdl/testbenches/jesd_loopback/runs/cfg2_np12/system_project.log] ...
Building cfg3_np12_L2M8 env [/home/me/Documents/adi/hdl/testbenches/jesd_loopback/runs/cfg3_np12_L2M8/system_project.log] ...
Building cfg4_F8 env …
```
=> Lock cfgs, fix printed message, include .gitignore

ad7616/system_bd.tcl, ad7616/system_tb.sv, ad7616/tests/test_program_si.sv
Rename the "irq" port into "ad7616_irq", as the "irq" will be used in the common test harness.
=> ad7616: Rename irq port

ad463x/Makefile, ad463x/system_project.tcl, ad463x/tests/test_program.sv, ad7606x/tests/test_program.sv, ad7616/Makefile, ad7616/system_project.tcl, ad7616/tests/test_program_pi.sv, ad7616/tests/test_program_si.sv, pulsar_adc_pmdz/Makefile, pulsar_adc_pmdz/system_project.tcl, pulsar_adc_pmdz/tests/test_program.sv, pulsar_adc_pmdz/tests/test_sleep_delay.sv
Use the axi_pwm_gen.pkg across all the testbenches, delete the unnecessary delays related to pwm axi_writes and small cosmetic changes.
=> Use axi_pwm_gen package in all testbenches

ad7606x/system_bd.tcl, ad7606x/tests/test_program.sv, ad9083/system_bd.tcl, ad9083/tests/test_program.sv, ad_quadmxfe1_ebz/system_bd.tcl, ad_quadmxfe1_ebz/tests/test_dma.sv, ad_quadmxfe1_ebz/tests/test_program.sv, ad_quadmxfe1_ebz/tests/test_program_64b66b.sv, adrv9001/system_bd.tcl, adrv9001/tests/test_program.sv, adrv9009/system_bd.tcl, adrv9009/tests/test_program.sv, axi_tdd/system_bd.tcl, axi_tdd/tests/test_program.sv, dma_loopback/system_bd.tcl, dma_loopback/tests/test_program.sv, fmcomms2/system_bd.tcl, fmcomms2/tests/test_program.sv, jesd_loopback/system_bd.tcl, jesd_loopback/tests/test_program.sv, jesd_loopback_64b/system_bd.tcl, jesd_loopback_64b/tests/test_program.sv, mxfe/cfgs/cfg1.tcl, mxfe/cfgs/cfg2_64b66b_np8.tcl, mxfe/cfgs/cfg3_64b66b_np12.tcl, mxfe/cfgs/cfg4_8b10b_np12.tcl, mxfe/cfgs/cfg5_204c_txmode_10_rxmode_11.tcl, mxfe/system_bd.tcl, mxfe/tests/test_program.sv
Definition of base addresses up until this point happened at both block design and testbench level, which could lead to errors. 
Define the address at block design level and pass the parameter as definition to the testbench.
=> Define the base addresses at block design level

ad463x/tests/test_program.sv, ad7606x/tests/test_program.sv, ad7616/tests/test_program_pi.sv, ad7616/tests/test_program_si.sv, ad_quadmxfe1_ebz/tests/test_dma.sv, adrv9001/tests/test_program.sv, adrv9009/tests/test_program.sv, axi_tdd/tests/test_program.sv, data_offload/tests/test_program.sv, data_offload_2/tests/test_program.sv, data_offload_2/tests/test_program_sync.sv, dma_loopback/tests/test_program.sv, fmcomms2/tests/test_program.sv, i3c_controller/system_bd.tcl, i3c_controller/tests/test_program.sv, pulsar_adc_pmdz/tests/test_program.sv, pulsar_adc_pmdz/tests/test_sleep_delay.sv, spi_engine/tests/test_program.sv, spi_engine/tests/test_sleep_delay.sv
Add parentheses to function calls to differentiate them from variables for readability.
=> Differentiate function calls from variables

scripts/project-sim.mk
Backslashes are not propagated by flock, so they do not reach Vivado.
Since Vivado tclsh supports unix-like paths, use them instead of escaping backslashes.
Also defines sh as the shell called by flock, since we want to ensure support to sh shell (related to https://github.com/analogdevicesinc/hdl/pull/1303).
The documentation for cygpath can be [read here](https://cygwin.com/cygwin-ug-net/cygpath.html),
where I chose "mixed mode" for the unix-like path, e.g.:
```
/cygdrive/c/Users/ --> C:/Users/
```
The flock behavior can be tested with:
```
~$ echo hello \\ backslash!
hello \ backslash!
~$ flock temp -c "echo hello \\ backslash!"
hello  backslash!
```
Vivado tclsh behavior can be tested with:
```
cd c:/Users
OK
cd c:\Users
couldn't change working directory to "c:Users": no such file or …
```
=> scripts: fixup cygwin, use sh as subshell

common/sv/adi_regmap_i3c_controller_pkg.sv, i3c_controller/cfgs/cfg1.tcl, i3c_controller/cfgs/cfg2.tcl, i3c_controller/system_bd.tcl, i3c_controller/tests/test_program.sv
Test when the controller is listening for IBIs but the feature itself is disabled.
Regenerate adi_regmap_i3c_controller_pkg.sv using the perl script.
=> i3c_controller: Add IBI corner case test

scripts/project-sim.mk
CI skips tests for which the system build failed. 
In these cases the test program will not be started, instead it will state that the test program is skipped. This will also be shown in the CI history:
- System builds will be noted as `FAILED`
- Test programs that fail to pass the test but have successfully built systems will be noted as `FAILED`
- Test programs that don't have successfully built systems will be noted as `SKIPPED`
By default, running on local machine, once the system build fails, the test program is not started. 
How to check:
- Run all tests with the following make command: `make STOP_ON_ERROR=n`
Tested cases:
1) _ADRV9009_:
- Since the system build fails, this a good example
- Run the make script from above
2) _Scoreboard_:
- Create a copy of `cfg1` and name it `cfg2` …
=> CI - skip tests for failed system builds

ad463x/tests/test_program.sv, ad738x/tests/test_program.sv, ad7616/tests/test_program_si.sv, pulsar_adc_pmdz/tests/test_program.sv, pulsar_adc_pmdz/tests/test_sleep_delay.sv
Sanity test update regarding version. Whenever the SPI engine version is updated, if the regmap version is updated, the new version value is seen by all testbenches that use this IP. 
Merge after [PR](https://github.com/analogdevicesinc/testbenches/pull/115)
=> spi_engine: Updated sanity tests for affected projects

pulsar_adc_pmdz/system_project.tcl
CI error: 
`ERROR: [Vivado 12-172] File or Directory 'tests/test_sleep_delay.sv' does not exist`
Removed the entry from system_project.
=> pulsar: Remove leftover test_program

common/sv/m_axis_sequencer.sv, common/sv/x_monitor.sv
- Added support for non-valid byte transmission using keep
- Added support for the monitor to drop non-valid signals for scoreboard
Strobe signal verification was added for AXI4 transmissions. Functionality wasn't tested. 
Plan: modify DMA to support non-valid bytes with keep and strobe signals to properly test functionality in cases where not all data bytes are valid.
=> m_axis_sequencer: Updated keep signal

pluto/Makefile, pluto/README.md, pluto/cfgs/cfg1.tcl, pluto/system_bd.tcl, pluto/system_project.tcl, pluto/system_tb.sv, pluto/tests/test_program.sv, pluto/waves/cfg1.wcfg
This commit adds a new testbench for Pluto operating in both 1R1T and 2R2T modes, including the TDD setup and testing.
=> Add testbench for Pluto

.gitignore
now it correctly ignores .lock files from libraries
=> .gitignore: fix ignoring all .lock files

docs/testbenches/common/more_information.rst, docs/testbenches/ip_based/index.rst, docs/testbenches/ip_based/template/index.rst, docs/testbenches/project_based/index.rst, docs/testbenches/project_based/template/index.rst
Update the "More information" file to send the user to the "User guide" section.
Hide the ip-based and project-based template files from the toctree.
=> Doc quickfixes

testbenches/project/ad7616/system_project.tcl
Using the 7-series Xilinx FPGA part, since the original Ultrascale+ part has different properties and requirements for the MMCM clock generation and the AD7616 project implementation is only available for Zedboard. 
This fix is proposed since the latest update on the HDL for adding the FPGA_TECHNOLOGY for VCU boards affects the axi_clk_gen IP used in this project. Other projects are unaffected by this change.
=> ad7616: Updated FPGA part number

docs/testbenches/project_based/index.rst, docs/testbenches/project_based/pulsar_adc/index.rst, docs/testbenches/project_based/pulsar_adc/pulsar_adc_pmdz_tb.svg
Add documentation support for the PulSAR ADC testbench.
=> docs: Add PulSAR ADC doc

scripts/make_tb_path.mk
Add informative error for mandatory environment variable.
I would rather "hardcode" the depth on the entry Makefile (the one that we can obtain the current shell path),
and infer these variables for most users.
=> scripts: make_tb_path: Error for unset ADI_*_DIR

docs/conf.py, docs/requirements.txt
Sphinx-wavedrom [deps: cairocffi, CairoSVG] don't seem to be tested continuously, which leads to fatal bugs reaching production. The extension in particular has  two red flags:
* It renders on the client side, requiring wavedrom.js to be fetched from a different from a different domain, slowing down or even preventing the documentation if the domain is offline (cause of a previous problem).
* Even though it renders on the client side in our user case, it still import cairo renderer during build (the root cause of the current issue)
Drop it in favor of just committing the wavedrom source (commented out in the page or as a text file in the same path) and the rendered svg.
Also, reorder requirements to have adi_doctools as the first requirement.
You can check the checkboxes below by …
=> docs: Drop wavedrom, reorder requirements

docs/testbenches/ip_based/dma_flock/block_diagram.svg, docs/testbenches/ip_based/dma_flock/index.rst
=> docs: Add ip_based dma_flock testbench

testbenches/ip/i3c_controller/system_bd.tcl, testbenches/ip/i3c_controller/tests/test_program.sv, testbenches/ip/i3c_controller/waves/cfg1.wcfg
TB update for https://github.com/analogdevicesinc/hdl/pull/1514
=> i3c_controller: Add I2C_MOD parameter

docs/user_guide/coding_guidelines.rst
Coding guideline for testbenches
=> docs: Initial coding guidelines

library/vip/amd/axi/adi_axi_agent.sv, library/vip/amd/axi/adi_axi_monitor.sv, library/vip/amd/axi/m_axi_sequencer.sv, library/vip/amd/axis/adi_axis_agent.sv, testbenches/ip/util_axis_fifo/Makefile, testbenches/ip/util_axis_fifo/README.md, testbenches/ip/util_axis_fifo/cfgs/cfg_rand.tcl, testbenches/ip/util_axis_fifo/environment.sv, testbenches/ip/util_axis_fifo/system_bd.tcl, testbenches/ip/util_axis_fifo/system_project.tcl, testbenches/ip/util_axis_fifo/system_tb.sv, testbenches/ip/util_axis_fifo/tests/test_program.sv, testbenches/ip/util_axis_fifo/waves/cfg_rand.wcfg, testbenches/ip/util_axis_fifo_asym/environment.sv
Use this branch for the HDL repository: [util axis fifo branch](https://github.com/analogdevicesinc/hdl/pull/1287)
To be merged after [this PR](https://github.com/analogdevicesinc/testbenches/pull/77)
=> Util axis fifo tb

scripts/adi_sim.tcl
Update the adi_sim script to default to non-coherent interfaces in testbenches.
=> scripts: adi_sim: Default to noncoherent interface

library/utilities/test_harness_env.sv
Added simulation watchdog that restricts the runtime of all testbenches to 1 millisecond, preventing simulation hangs.
This value can be adjusted for each individual testbench to reduce the overhead.
=> test_harness_env: Added simulation watchdog

docs/testbenches/ip_based/util_axis_fifo_asym/index.rst, testbenches/ip/util_axis_fifo_asym/cfgs/cfg_rand.tcl, testbenches/ip/util_axis_fifo_asym/system_bd.tcl
Updated testbench parameterization and documentation according to HDL changes found in [this PR](https://github.com/analogdevicesinc/hdl/pull/1719).
=> util_axis_fifo_asym: Updated testbench

docs/testbenches/ip_based/i3c_controller/index.rst, library/regmaps/adi_regmap_i3c_controller_pkg.sv, testbenches/ip/i3c_controller/Makefile, testbenches/ip/i3c_controller/cfgs/cfg1.tcl, testbenches/ip/i3c_controller/cfgs/cfg2.tcl, testbenches/ip/i3c_controller/system_bd.tcl, testbenches/ip/i3c_controller/tests/test_program.sv
Pair pr of https://github.com/analogdevicesinc/hdl/pull/1724
Removed from the I3C controller IP core.
Add write DAA mock task  To emulate a device writing the PID+BCR+DCR during the dynamic address assignment.
=>  i3c_controller: Remove CLK_MOD, small write DAA task

library/vip/amd/axis/m_axis_sequencer.sv, testbenches/ip/util_axis_fifo_asym/Makefile, testbenches/ip/util_axis_fifo_asym/cfgs/cfg_tkeep.tcl, testbenches/ip/util_axis_fifo_asym/system_project.tcl, testbenches/ip/util_axis_fifo_asym/tests/test_tkeep.sv, testbenches/ip/util_axis_fifo_asym/waves/cfg_tkeep.wcfg
- Add support for user-defined tkeep on m_axis_sequencer,
- Add test_tkeep to util_axis_fifo, with random tkeep
- Add cfg_tkeep to util_axis_fifo, which forces TKEEP_EN=1
=> testbenches/ip/util_axis_fifo: include test with random tkeep
